### PR TITLE
Fix topology test

### LINKED ISSUE #53: Topology module memory leaks
**Describe the bug**
The topology module, apparently, has several memory leaks.

**To Reproduce**
Run ```test_topology``` under Valgrind.

As a side note: the topology module is not necessary to the functioning of the core library, is not used by any model and probably should be moved to the cROOT-Sim repository.

### PR DESCRIPTION
**Pull request by alessandropellegrini**
This PR fixes a couple of memory leaks in the topology library.
This fixes #53

### CODE REVIEW

**Comment by alessandropellegrini** [comment]
This PR also fixes the undefined behaviour spotted in d5e77972f788d857839ae134eacc570c1ecae229.

File: test/framework/test.c [hunk 1]
```diff
@@ -32,15 +32,10 @@ void finish(void)
...
+void test_init(unsigned n_th)
 {
-	if(setjmp(test_unit.fail_buffer)) {
-		test_unit.ret = -1; // getting here from fail()
-		finish();
-	}
-
 	test_random_init();
-	global_config.n_threads = n_th;
+	global_config.n_threads = (n_th);
```
Comment (Piccions) [inline test/framework/test.c:38]: Not important: forgot the parentheses around n_th

**Review by Piccions — APPROVED** [review]
Thanks for the work!
